config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get "/about" => "pages#about"
  get "/contact" => "pages#contact"
  get "/news" => "pages#news"

  resources :users
  resources :events, except: %i[new create] do
    resources :tickets, only: %i[new create] do
      resources :orders, only: %i[new create]
    end
  end
  resources :tickets, except: %i[new create]
  resources :orders, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  validates :local, presence: true
  validates :date, presence: true
  validates :artist, presence: true
  validates :age_rating, presence: true, numericality: { only_integer: true }

  has_many :tickets, dependent: :destroy
  #has_one_attached :photo
end

app/models/order.rb
class Order < ApplicationRecord
  validates :pay_method, presence: true

  belongs_to :user
  belongs_to :ticket
  belongs_to :event
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user
  belongs_to :event


  validates :sector, presence: true
  # validates :category, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tickets, dependent: :destroy

  # validates :name, presence: true, length: { minimum: 2 }
  # validates :phone_number, presence: true, numericality: { only_integer: true }
  # validates :birth_date, presence: true
  # validates :id_document, presence: true, uniqueness: true
  # validates :address, presence: true
  # validates :email, presence: true, uniqueness: true
  # validates :encrypted_password, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # [...]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :phone_number, :address, :birth_date, :id_document, :avatar, :allow_alert])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :phone_number, :address, :birth_date, :id_document, :avatar, :allow_alert])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  def index
    @events = Event.all
  end

  # GET /events/1
  def show
    @event = Event.find(params[:id])
    @tickets = @event.tickets
  end

# GET /events/new
  def new
    @event = Event.new
  end

# GET /events/1/edit
  def edit
  end

# POST /events
  def create
    @event = Event.new(event_params)

    if @event.save
      redirect_to @event, notice: 'Event was successfully created.'
    else
      render :new
    end
  end

# PATCH/PUT /events/1
  def update
    if @event.update(event_params)
      redirect_to @event, notice: 'Event was successfully updated.'
    else
      render :edit
    end
  end

# DELETE /events/1
  def destroy
    @event.destroy
    redirect_to events_url, notice: 'Event was successfully destroyed.'
  end

private

# Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

# Only allow a trusted parameter "white list" through.
  def event_params
    params.require(:event).permit(:title, :body, :photo)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_action :set_ticket, only: [:new, :create]
  before_action :set_user, only: [:new, :create]
  before_action :set_event, only: [:new, :create]
  before_action :authenticate_user!, only: [:create, :index]

  def index
    @orders = Order.where(user: current_user)
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    @order.user = @user
    @order.event_id = @event.id
    @order.ticket_id = @ticket.id
    if @order.save
      redirect_to orders_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    redirect_to user_path(@order.user), status: :see_other
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = current_user
  end

  def set_event
    @event = Event.find(params[:event_id])
  end

  def set_ticket
    @ticket = Ticket.find(params[:ticket_id])
  end

  def order_params
    params.require(:order).permit(:pay_method)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
  end

  def about
  end

  def contact
  end

  def news
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: %i[show edit update destroy]
  before_action :set_user, only: %i[new create edit update]
  before_action :set_event, only: %i[new create edit update]
  before_action :authenticate_user!

  def index
    @tickets = Ticket.all
    render :index
  end

  def show
    @ticket = Ticket.find(params[:id])
    render :show
  end

  def new
    @ticket = Ticket.new
    render :new
  end

  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.user = @user
    @ticket.event = @event
    if @ticket.save
      redirect_to event_path(@event)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @ticket = Ticket.find(params[:id])
    render :edit
  end

  def update
    @ticket = Ticket.find(params[:id])
    @ticket.update(ticket_params)
    redirect_to ticket_path(@ticket)
  end

  def destroy
    @ticket = Ticket.find(params[:id])
    @ticket.destroy
    redirect_to user_path(@ticket.user), status: :see_other
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = current_user
  end

  def set_event
    @event = Event.find(params[:event_id])
  end

  def ticket_params
    params.require(:ticket).permit(:price, :category, :sector)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
    @user = User.find(params[:id])
    render :show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to root_path, notice: 'User was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def user_params
    params.require(:user).permit(:name, :phone_number, :birth_date, :id_document, :country, :address, :password, :allow_alert)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def humanize(tab)
    tab.titleize
  end
end

app/views/events/show.html.erb
<%= render "shared/banner" %>

<div class="mt-4 p-3" style="font-family: 'Indie Flower', cursive;">
    <div class="col-md-12">
      <div class="description">
        <h2>Descrição</h2>
        <p><%= @event.description %></p>

        <h2>Local</h2>
        <p><%= @event.local %></p>
      </div>
    </div>
  <div class="row">
    <div class="card-arena col-md-8">
      <%= image_tag 'https://res.cloudinary.com/dxf2n51ev/image/upload/v1715969622/middleLeWagon/Arenas/tjowpr6d043nl3jf9wwg.png' %>
    </div>
    <div class="col-md-4">
      <div class="container tickets-available">
        <ul class="list-group">
          <% @tickets.each do |ticket| %>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              <div>
                <span class="mr-2">Setor: <%= ticket.sector %> - <%= ticket.category.join(", ") %></span>
                <span class="mr-2">R$<%= sprintf("%.2f", ticket.price) %></span>
              </div>
              <%= link_to "Comprar ingresso", new_event_ticket_order_path(@event, ticket), class: "btn btn-primary" %>
            </li>
          <% end %>
        </ul>
        </div>
      </div>
      <div class="sell-ticket">
        <%= link_to "Vender ingresso", new_event_ticket_path(@event.id), class: "btn btn-success" %>
      </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Middle</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div>
      <%= render "shared/navbar" %>
      <%= yield %>
      <%= render "shared/footer" %>
      <%= render "shared/flashes" %>
    </div>
  </body>
</html>

app/views/orders/index.html.erb
<div class="banner p-5" style="background: linear-gradient(90deg, rgba(2,0,36,1) 0%, rgba(9,9,121,1) 35%, rgba(0,212,255,1) 100%);">
  <h1 class="display-4" style="color: white;">Sua compra</h1>
</div>

<div class="mt-4" style="font-family: 'Indie Flower', cursive;" >
    <div class="col-md-12">
      <div class="description container">
        <% @orders.group_by(&:event).each do |event, orders| %>
            <div class="container">
            <h2><%= event.artist %></h2>
            <p><%= event.local %></p>
            <p><%= "Número de pedidos: #{orders.size}" %></p>
            </div>
        <% end %>
      <h4>Enviamos um email com os detalhes da sua compra. Siga as instruções para confirmar o pagamento e receber o seu ingresso de forma online e prática. 😉</h4>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/orders/new.html.erb
<%= render "shared/banner" %>

<div class="mt-4" style="font-family: 'Indie Flower', cursive;" >
    <div class="col-md-12">
      <div class="description container">
        <h2>Confirm your purchase</h2>
        <h4>Local: <%= @event.local %></h4>
        <h4>Ticket price: R$<%= @ticket.price %></h4>
        <h4>Category: <%= @ticket.category.join %></h4>
        <div class="container m-2">
          <%= simple_form_for [@event, @ticket, @order] do |f| %>
          <%= f.input :pay_method, collection: ["Credit Card", "PayPal"] %>
            <%= f.submit "Buy ticket", class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/about.html.erb
 <div class="container mt-5" style="font-family: 'Indie Flower', cursive;">
        <h2 class="mb-4">Sobre o Middle</h2>
        <p>
            O <strong>Middle</strong> nasceu da paixão pela música e entretenimento ao vivo. Fundado em 2010 por um grupo de amigos apaixonados por shows e festivais, o Middle começou como uma plataforma simples para conectar fãs a eventos musicais em sua cidade. O nome "Middle" foi escolhido como uma homenagem ao momento mágico que ocorre no meio de um show, quando a música, a energia da multidão e a emoção se unem.
        </p>
        <p>
            Nosso propósito é tornar a experiência de comprar ingressos para shows mais fácil, segura e acessível para todos. Queremos eliminar as filas intermináveis, os sites confusos e as taxas ocultas. Acreditamos que todos devem ter a oportunidade de vivenciar a magia de um concerto ao vivo, independentemente de seu gosto musical ou orçamento.
        </p>
        <h2 class="mb-4">Como Funciona</h2>
          <ol>
          <li>Compra e Comparação de Ingressos:
            <ul>
              <li>No Middle, você pode pesquisar e comparar ingressos para shows de diferentes artistas, gêneros e locais.</li>
              <li>Nossa interface intuitiva permite que você veja preços, disponibilidade e opções de assentos em um só lugar.</li>
            </ul>
          </li>
          <li>Segurança e Transparência:
            <ul>
              <li>Trabalhamos com parceiros confiáveis e garantimos que todos os ingressos sejam autênticos e válidos.</li>
              <li>Não cobramos taxas escondidas. O preço que você vê é o preço que paga.</li>
              <li>Oferecemos suporte ao cliente 24 horas por dia, 7 dias por semana, para ajudá-lo com qualquer dúvida ou problema.</li>
            </ul>
          </li>
          <li>Comunidade de Fãs:
            <ul>
              <li>O Middle é mais do que apenas um site de vendas de ingressos. É uma comunidade de fãs apaixonados.</li>
              <li>Compartilhe suas experiências, descubra novos artistas e conecte-se com outros amantes da música.
</li>
            </ul>
          </li>
          </ol>
    </div>

app/views/pages/contact.html.erb
    <div class="container mt-5" style="font-family: 'Indie Flower', cursive;">
      <h2 class="mb-4">Entre em contato</h2>
      <form action="/enviar-contato" method="post">
        <%= csrf_meta_tags %>
        <div class="form-group">
          <label for="nome">Nome:</label>
          <input type="text" id="nome" name="nome" class="form-control" required>
        </div>
        <div class="form-group">
          <label for="email">E-mail:</label>
          <input type="email" id="email" name="email" class="form-control" required>
        </div>
        <div class="form-group">
          <label for="mensagem">Mensagem:</label>
          <textarea id="mensagem" name="mensagem" class="form-control" rows="5" required></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Enviar</button>
      </form>
    </div>

app/views/pages/home.html.erb
<div class="row justify-content-center">
  <% Ticket.all.each do |ticket| %>
    <div class="col-md-2 col-sm-4 col-xs-6 m-3">
      <%= link_to "/events/#{ticket.event.id}", class: "card m-2 h-100", id: "card-#{ticket.id}" do %>
        <%= image_tag ticket.event.photo, class: "card-image", alt: "Card image", style: "width: 100%" %>
        <div class="card-body">
          <h5 class="card-title text-truncate"><%= ticket.event.artist %></h5>
          <p class="card-price">R$ <%= sprintf("%.2f", ticket.price) %></p>
        </div>
      <% end %>
    </div>
  <% end %>
</div>
</div>

<script>
  var searchInput = document.getElementById('searchInput');
  var cards = document.querySelectorAll('.card');
  var images = document.querySelectorAll('.card-image');

  searchInput.addEventListener('input', filterCards);


  function filterCards() {
    var searchValue = searchInput.value.toLowerCase();

    cards.forEach((card, index) => {
      var cardContent = card.textContent.toLowerCase();
      if (cardContent.includes(searchValue)) {
        card.style.display = 'block';
        images[index].style.display = 'block';
        card.classList.add('visible-card'); // Add CSS class to visible cards
      } else {
        card.style.display = 'none';
        images[index].style.display = 'none';
        card.classList.remove('visible-card'); // Remove CSS class from non-visible cards
      }
    });

    }

</script>

app/views/pages/news.html.erb
<div class="container" style="font-family: 'Indie Flower', cursive;">
  <h1 class="text-center mt-5">Notícias da semana</h1>
  <div class="row col-12">
    <div class="col-md-6">
      <div class="card mb-4">
        <div class="card-body">
          <h2 class="card-title"><a href="#">Novo Álbum de John Smith</a></h2>
          <p class="card-text">John Smith lançou seu mais recente álbum, intitulado "Harmonia Celestial". O álbum combina elementos de jazz e música clássica.</p>
        </div>
      </div>
      <div class="card mb-4">
        <div class="card-body">
          <h2 class="card-title"><a href="#">Turnê Mundial de Maria Garcia</a></h2>
          <p class="card-text">Maria Garcia, a talentosa violinista, está atualmente em uma turnê mundial. Ela se apresentará em várias cidades nos próximos meses.</p>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card mb-4">
        <div class="card-body">
          <h2 class="card-title"><a href="#">Entrevista com Carlos Rodríguez</a></h2>
          <p class="card-text">O famoso guitarrista Carlos Rodríguez concedeu uma entrevista exclusiva sobre sua carreira e influências musicais.</p>
        </div>
      </div>
      <div class="card mb-4">
        <div class="card-body">
          <h2 class="card-title"><a href="#">Prêmio para a Banda Rockstar</a></h2>
          <p class="card-text">A banda Rockstar ganhou o prêmio de "Melhor Performance ao Vivo" no Music Awards deste ano.</p>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card mb-4">
        <div class="card-body">
          <h2 class="card-title"><a href="#">Descoberta de Novo Talento</a></h2>
          <p class="card-text">Uma jovem cantora chamada Emily White está ganhando destaque nas redes sociais com sua voz poderosa.</p>
        </div>
      </div>
      <div class="card mb-4">
        <div class="card-body">
          <h2 class="card-title"><a href="#">Colaboração Inesperada</a></h2>
          <p class="card-text">Os rappers Jay-Z e Kendrick Lamar anunciaram uma colaboração surpresa em uma nova faixa.</p>
        </div>
      </div>
      
    </div>
    <!-- Adicione mais notícias aqui -->
  </div>
</div>

app/views/shared/_banner.html.erb
<div class="banner p-5" style="background: linear-gradient(90deg, rgba(2,0,36,1) 0%, rgba(9,9,121,1) 35%, rgba(0,212,255,1) 100%);">
  <h1 class="display-4" style="color: white;"><%= @event.artist %></h1>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="text-white text-center fixed-bottom bg-dark py-2">
  <p>© <%= Time.now.year %> Middle</p>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    <%= link_to root_path do %>
      <%= image_tag "https://res.cloudinary.com/dxf2n51ev/image/upload/v1715969514/middleLeWagon/jcxuubn1heth9lukwn7s.png", class: "logo img-fluid", alt: "logo", style: "width: 70%; height: auto;" %>
    <% end %>
  </a>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="container">
    <div class="collapse navbar-collapse" id="navbarNav">
      <div class="input-group">
        <input type="text" id="searchInput"class="form-control" placeholder="Search...">
        <div class="input-group-append">
          <button class="btn btn-outline-secondary" type="button">Search</button>
        </div>
      </div>
    </div>
  </div>
  <ul class="navbar-nav " style="margin-right: 50px;">
    <li class="nav-item mb-2">
      <%= link_to root_path, class: "nav-link" do %>
        <i class="fas fa-home"></i> Home
      <% end %>
    </li>
    <li class="nav-item mb-2">
      <%= link_to news_path, class: "nav-link" do %>
        <i class="fas fa-newspaper"></i> News
      <% end %>
    </li>
    <li class="nav-item mb-2">
      <%= link_to contact_path, class: "nav-link" do %>
        <i class="fas fa-envelope"></i> Contact
      <% end %>
    </li>
    <li class="nav-item mb-2">
      <%= link_to about_path, class: "nav-link" do %>
        <i class="fas fa-info-circle"></i> About
      <% end %>
    </li>
    <li class="nav-item mb-2">
      <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          <%= image_tag "https://res.cloudinary.com/dxf2n51ev/image/upload/v1715969514/middleLeWagon/iw3ty112ptpe7jtmwbre.png", class: "avatar-large", alt: "avatar-large", style: "width: 50px; height: 50px;" %>
        </button>
        <ul class="dropdown-menu">
          <% if user_signed_in? %>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %></li>
            <li><%= link_to "Meus Tickets", tickets_path, class: "dropdown-item" %></li>
            <li><%= link_to "Meu Perfil", users_path, class: "dropdown-item" %></li>
          <% else %>
            <li><%= link_to "Login", new_user_session_path, class:"dropdown-item" %></li>
          <% end %>
        </ul>
      </div>
    </li>
  </ul>
</nav>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

app/views/tickets/new.html.erb
<%= render "shared/banner" %>

<h1>Cadastre seu ingresso</h1>
<%= simple_form_for [@event, @ticket] do |f| %>
  <%= f.input :price, label: "Preço" %>
  <%= f.input :sector, label: "Setor" %>
  <%# <%= f.input :event, collection: Event.all.map { |event| [event.artist, event.id] }, label: "Evento" %>
  <%= f.input :category, collection: [['VIP'], ['Regular'], ['Economy']], label: "Categoria" %>
  <%= f.submit "Vender ingresso", class: "btn btn-primary" %>
<% end %>

app/views/users/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-12 text-center">
      <!-- User Avatar -->
      <%= image_tag @user.avatar, class: "avatar-large", alt: "avatar-large", style: "width: 120px; height: 120px;" %>
    </div>
    <div class="col-md-8 mx-auto">
      <div class="card">
        <h1 class="display-4 text-center"><%= @user.name %></h1>
        <div class="card-body">
          <ul class="nav nav-tabs justify-content-center">
            <li class="nav-item">
              <a class="nav-link active" data-tab="personal-info" href="#">Informações Pessoais</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" data-tab="security-privacy" href="#">Segurança e Privacidade</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" data-tab="preferences" href="#">Preferências</a>
            </li>
          </ul>
          <div class="tab-content mt-3">
            <div class="tab-pane fade show active" id="personal-info">
              <p class="lead editable">Email: <%= @user.email %></p>
              <p class="lead editable">Telefone: <%= @user.phone_number %></p>
              <p class="lead editable">Data de Nascimento: <%= @user.birth_date %></p>
              <p class="lead editable">CPF: <%= @user.id_document %></p>
              <p class="lead editable">Endereço: <%= @user.address %></p>
            </div>
            <div class="tab-pane fade" id="security-privacy">
              <p class="lead">Senha: <span id="password" class="password"><%= @user.encrypted_password %></span><button id="toggle-password-btn" class="btn btn-link"><i class="fas fa-eye"></i></button></p>
            </div>
            <div class="tab-pane fade" id="preferences">
              <form>
                <div class="form-group">
                  <label for="language">Idioma:</label>
                  <select class="form-control" id="language" name="language">
                    <option value="French">Português (BR)</option>
                    <option value="English">Inglês</option>
                    <option value="Spanish">Espanhol</option>
                    <option value="French">Francês</option>
                  </select>
                </div>
                <div class="form-group">
                  <label for="currency">Moeda:</label>
                    <select class="form-control" id="currency" name="currency">
                    <option value="BRL">BRL</option>
                    <option value="USD">USD</option>
                    <option value="EUR">EUR</option>
                    <option value="JPY">JPY</option>
                    </select>
                  </select>
                </div>
                <div class="form-group">
                  <label for="theme">Tema:</label>
                  <select class="form-control" id="theme" name="theme">
                    <option value="Light">Claro</option>
                    <option value="Dark">Escuro</option>
                    <option value="Colorful">Colorido</option>
                  </select>
                </div>
              </form>
            </div>
          </div>
        </div>
        <!-- Botão de Excluir -->
      </div>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col-md-12 text-center">
      <button id="edit-profile-btn" class="btn btn-primary">Editar Perfil</button>
      <%= link_to "Voltar para a Página Inicial", root_path, class: "btn btn-secondary" %>
      <button id="delete-account-btn" class="btn btn-danger">Excluir Conta</button>
    </div>
  </div>
</div>

<script>
  const togglePassword = document.querySelector("#toggle-password-btn");
  const password = document.querySelector("#password");

  togglePassword.addEventListener("click", function () {
    // Toggle the 'type' attribute between "text" and "password"
    const type = password.getAttribute("type") === "password" ? "text" : "password";
    password.setAttribute("type", type);

    // Toggle the icon
    this.querySelector("i").classList.toggle("bi-eye");
    this.querySelector("i").classList.toggle("bi-eye-slash");
  });

  // Prevent form submission
  const form = document.querySelector("form");
  form.addEventListener("submit", function (e) {
    e.preventDefault();
  });

  // Get all tab links
  var tabLinks = document.querySelectorAll('.nav-link');

  // Add click event listeners to each tab link
  tabLinks.forEach(tabLink => {
    tabLink.addEventListener('click', (event) => {
      console.log('clicado');
      event.preventDefault();

      // Get the target tab ID from the data-tab attribute
      const targetTabId = tabLink.getAttribute('data-tab');

      // Remove a classe 'active' de todos os links de guia e painéis de guia
      tabLinks.forEach(link => link.classList.remove('active'));
      document.querySelectorAll('.tab-pane').forEach(pane => pane.classList.remove('show', 'active'));

      // Add the 'active' class to the clicked tab link and show the corresponding tab panel
      tabLink.classList.add('active');
      document.getElementById(targetTabId).classList.add('show', 'active');
    });
  });

  // Add click event listener to the "Edit Profile" button
  var editProfileBtn = document.getElementById('edit-profile-btn');
  editProfileBtn.addEventListener('click', (event) => {
    event.preventDefault();

    // Toggle the content of all editable elements between editable and non-editable states
    //document.querySelectorAll('.form-control').forEach(element => {
      //element.contentEditable = !element.isContentEditable;
      //element.classList.toggle('form-control');
   // });
  // Change the button text based on the current state
    editProfileBtn.textContent = editProfileBtn.textContent === 'Editar Perfil' ? 'Salvar Perfil' : 'Editar Perfil';
  });
</script>